### ISSUE TITLE
GLPI 9.1.4

### ISSUE THREAD

**Issue by Smiley-k** [ddurieux/glpi_app_grafana#1]
No work, and no imported template grafana.

**Comment by ddurieux** [comment]
Ah? how do you installed it? (it will be more easier when be published, so in very few days)

**Comment by Smiley-k** [comment]
I copied the folder  **glpi_app_grafana** in  /var/lib/grafana/plugins .

In grafana
![image](https://user-images.githubusercontent.com/11009787/27534538-082ea9e4-5a70-11e7-96f4-819fef37ca67.png)

Settings data source
![2017-06-26 13 05 40](https://user-images.githubusercontent.com/11009787/27534603-45140eee-5a70-11e7-8d91-19d34b92ea59.png)

**Comment by ddurieux** [comment]
You need define  the `user token` related to the account in GLPI.

**Comment by Smiley-k** [comment]
Yes, of course. this data is provided
![2017-06-26 13 45 05](https://user-images.githubusercontent.com/11009787/27535984-b8f62360-5a75-11e7-98f7-b5abaa2b9e5e.png)

**Comment by ddurieux** [comment]
In GLPI, you have right allow the IP of your grafana in the API ?

Perhaps try use access `direct` instead `proxy`

What version of grafana you use? I have developped on grafana 4

**Comment by Smiley-k** [comment]
1) Yes.
![image](https://user-images.githubusercontent.com/11009787/27536270-1081f9be-5a77-11e7-8032-431bf97f0006.png)
2) no, when using the directories have the error
![image](https://user-images.githubusercontent.com/11009787/27536297-3175bf20-5a77-11e7-8a52-530b15d1b69d.png)
3) version grafana  Grafana v4.3.2 (commit: ed4d170)

**Comment by ddurieux** [comment]
in `ipv4 address range` you must set it, try use something like `0.0.0.1 - 254.254.254.254` to allow all IP ;)

**Comment by Smiley-k** [comment]
no =( , I pointed out the IP grafana
![image](https://user-images.githubusercontent.com/11009787/27536558-6cbbf6ca-5a78-11e7-96ae-cafc930fa7d0.png)
 
the same error

 HTTP Error
Bad Request

**Comment by ddurieux** [comment]
Address range, you must specify the first IP and the last IP, not the netmask :D

**Comment by Smiley-k** [comment]
no, 
![image](https://user-images.githubusercontent.com/11009787/27538542-2297efa0-5a81-11e7-80de-26ef45ebef81.png)

HTTP Error
Bad Request

http://192.168.80.19/**apirest.php** right ?

**Comment by ddurieux** [comment]
the URL is right with GLPI 9.1.x...
Perhaps see your webserver logs

**Comment by Smiley-k** [comment]
In the web server when connecting from grafana reports the following

[26/Jun/2017:15:53:30 +0300] "GET /apirest.php/initSession HTTP/1.1" 400 184 "http://grafana.domain:3000/datasources/edit/5" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.168.80.30 - - [26/Jun/2017:15:53:36 +0300] "GET /apirest.php/initSession HTTP/1.1" 400 184 "http://grafana.domain:3000/datasources/edit/5" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.168.80.30 - - [26/Jun/2017:15:53:40 +0300] "GET /apirest.php/initSession HTTP/1.1" 400 184 "http://grafana.domain:3000/datasources/edit/5" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

**Comment by ddurieux** [comment]
I mean logs for GLPI, not Grafana ;)

**Comment by ddurieux** [comment]
I see the error, I'm working on a fix ;)

**Comment by ddurieux** [comment]
So no it works :p fine

**Comment by Smiley-k** [comment]
not working ?

27 июня 2017 г. 5:23 PM пользователь "David Durieux" <
notifications@github.com> написал:

**Comment by ddurieux** [comment]
I have a problem with my glpi (dev version not up-to-date), so now it works on last grfana  and on GLPI 9.1 and dev (9.2), so I think you have a configuration problem somewhere.... perhaps allow headers in you webserver deliver GLPI

**Comment by Smiley-k** [comment]
I have glpi 9.1.4

27 июня 2017 г. 5:28 PM пользователь "David Durieux" <
notifications@github.com> написал:

**Comment by ddurieux** [comment]
9.1.x works, so 9.1.4 works too :p

**Comment by Smiley-k** [comment]
but I have not worked =(

**Comment by Smiley-k** [comment]
`192.168.80.30 - - [27/Jun/2017:17:51:39 +0300] "GET /apirest.php/initSession HTTP/1.1" 400 184 "http://grafana.hub.domain:3000/datasources/edit/5" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"`

log on the web server glpi

`192.168.80.30 - this is the address where the message (from the server grafana)

**Comment by ddurieux** [comment]
Perhaps your webserver not allow CORS, it's required to work

**Comment by Smiley-k** [comment]
I don't know what to do to make it work
setting CORS done, but not working.

**Comment by ddurieux** [comment]
See the API page, http://yourglpi_url/apirest.php and you have all information at the end

**Comment by fulljackz** [comment]
Hi there,

I am running GLPI 9.1.4 with Apache 2.4.10 on Debian 8 from a side, and Grafana 4.4.3 with Apache on Debian 9 on another side.

I can't get your dashboard working with my current configuration. I looked at apirest.php, especially at the end, and no information about cors or apache headers.

My problem is probably linked with https://github.com/ddurieux/glpi_app_grafana/issues/3 but I can't find an issue to it.

Could you post a webserver conf example pls ?

Thanks !

**Comment by ddurieux** [comment]
For nginx: 
```
    server {
        listen       80;

        location / {
            root   /usr/local/www/nginx;
            index  index.php index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/www/nginx-dist;
        }

        more_set_headers 'Access-Control-Allow-Origin: *';
        more_set_headers 'Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE';
        more_set_headers 'Access-Control-Allow-Credentials: true';
        more_set_headers 'Access-Control-Allow-Headers: Origin,Content-Type,Accept,Authorization,App-Token,Session-Token';

        location /api {
             rewrite ^/api/(.*)$ /apirest.php/$1 last;
        }
 

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ [^/]\.php(/|$) {
            client_max_body_size 20M;
            root           html;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  HTTP_REFERER $http_referer;
            fastcgi_param  SCRIPT_FILENAME  /usr/local/www/nginx$fastcgi_script_name;
            include        fastcgi_params;
            fastcgi_param  SERVER_NAME      $host;
             
            set $path_info $fastcgi_path_info;
            fastcgi_param  PATH_INFO $path_info;
        }
    }
```

**Comment by klmj** [comment]
Hi there,

#### For Apache
Add the following line inside either the `<Directory>`, `<Location>`, `<Files>` or `<VirtualHost>` sections of your server config (usually located in a *.conf file, such as `httpd.conf` or `apache.conf`), or within a `.htaccess` file : 
````
<IfModule headers_module>
	Header set Access-Control-Allow-Origin "*"
	Header set Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE"
	Header set Access-Control-Allow-Credentials "true"
	Header set Access-Control-Allow-Headers "Origin,Content-Type,Accept,Authorization,App-Token,Session-Token"
</IfModule>
````

Regards

**Comment by ddurieux** [comment]
Thanks ;)

**Comment by ppierref** [comment]
I always get this error message
![image](https://user-images.githubusercontent.com/35942310/35543123-1f355ea8-0542-11e8-9001-d45bf09382e0.png)


![image](https://user-images.githubusercontent.com/35942310/35543067-dd898e3e-0541-11e8-8f2f-04a142de0b7a.png)

GLPI 9.2
Debian 9 - 64x
PHP 7.0.19-1
Apache/2.4.25

**Comment by ddurieux** [comment]
Open the `web developper` part of your browser and in network part, wee the url of your GLPI called by grafana

**Comment by ppierref** [comment]
![errografana](https://user-images.githubusercontent.com/35942310/35603744-7b012722-061d-11e8-85e7-53a82bd858ea.PNG)
![erro grafana](https://user-images.githubusercontent.com/35942310/35603768-9c6a5122-061d-11e8-9d71-325ebd00d7f9.PNG)

**Do I need to edit any files? How should I proceed - Apache/2.4.25**

**Comment by ddurieux** [comment]
See https://github.com/ddurieux/glpi_app_grafana/issues/1#issuecomment-343886892

with this modification, you need too have in httpd.conf the `AllowOverride All` to allow the use of the `.htaccess`

**Comment by ppierref** [comment]
Problem continues :'(
Even with version 9.1.4 of GLPI and Apache Server
![image](https://user-images.githubusercontent.com/35942310/36081913-29b9f082-0f83-11e8-858a-ca528c6283b5.png)
![image](https://user-images.githubusercontent.com/35942310/36081927-43ec8564-0f83-11e8-9b95-df2c258502d0.png)

**Comment by ddurieux** [comment]
The config seems good, but are you sure the module `headers_module` is installed and loaded? 
You have the `IfModule` so perhaps it's that

**Comment by ppierref** [comment]
Thanks ddurieux
![img1](https://user-images.githubusercontent.com/35942310/36399014-b504b476-15a8-11e8-984c-e485af58a598.png)
![img2](https://user-images.githubusercontent.com/35942310/36399019-b922f1a8-15a8-11e8-8a1e-464c0c75f0e2.png)
![img3](https://user-images.githubusercontent.com/35942310/36399023-bcb04a64-15a8-11e8-9b7d-31e866ed335c.png)
![img4](https://user-images.githubusercontent.com/35942310/36399025-bf8cc37a-15a8-11e8-9e5b-7624c73314e0.png)

**Comment by ppierref** [comment]
Insert lines in the file
#vim /etc/apache2/sites-enabled/**000-default.conf**

```
<IfModule headers_module>
  Header set Access-Control-Allow-Origin "*"
  Header set Access-Control-Allow-Methods "GET, HEAD, POST, OPTIONS, PUT, DELETE"
  Header set Access-Control-Allow-Credentials "true"
  Header set Access-Control-Allow-Headers "Origin,Content-Type,Accept,Authorization,App-Token,Session-Token,Access-Control-Request-Headers"
</IfModule>
```

Loaded module on apache
#`sudo a2enmod headers`

Restart service Apache
#`sudo service apache2 restart`

**Comment by ddurieux** [comment]
Very good news ^^

**Comment by siccbr** [comment]
Hello,

In spite of your explanations, I modified the set of configuration files but I still have the same error message.
In live mode it gives this:
,
![capture](https://user-images.githubusercontent.com/36511932/36471645-77c226d2-16ef-11e8-9a18-0aba5e216d2e.PNG)


The conf file is the follower (centos distribution for the GLPI and a debian for the grafana)

![capture](https://user-images.githubusercontent.com/36511932/36471726-ce438334-16ef-11e8-9ac6-3c2dd3c6d44d.PNG)


I also have an error message when I put in proxy mode: 
while I have GLPI I have indicated my ip

![capture](https://user-images.githubusercontent.com/36511932/36471836-2fccc958-16f0-11e8-8b57-9433033bdeec.PNG)


I thank you for the valuable help you can give me. Have a good day

PS: 
Excuse me if there are spelling mistakes, I'm french

**Comment by ddurieux** [comment]
In GLPI, in menu Setup > General, in tab API, you need modify the range IP allowed to access to GLPI. The message say, your IP not allowed (by default only 127.0.0.1 allowed).

**Comment by siccbr** [comment]
Thank you for the speed of the answer but I indicated the range of address without result

![capture](https://user-images.githubusercontent.com/36511932/36473228-3790e5da-16f4-11e8-9d1f-e6110903481d.PNG)

Ci dessous un exemple de configuration

![capture](https://user-images.githubusercontent.com/36511932/36473278-60532726-16f4-11e8-86ad-88feebbd3dc7.PNG)

**Comment by ddurieux** [comment]
Seems ok, to be sure, the app_token is not the same for _full access from localhost_ and _mon glpi2_ ? if yes, you will have problem, so perhaps try disable them

**Comment by allancarlosvr** [comment]
My problem is the same with @siccbr , But in my inspection of code i see this it. Anyone can help me?
![capturar](https://user-images.githubusercontent.com/36505009/36631696-7b8f4844-195b-11e8-9932-175cf2bfe914.PNG)

`angular.js:12759 Mixed Content: The page at 'https://monitor.sumicity.net.br/datasources/edit/18' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://10.99.1.121/apirest.php/initSession'. This request has been blocked; the content must be served over HTTPS.`

**Comment by ddurieux** [comment]
Seems your grafana in https and your GLPI api in http or invert (not sure). you can't mix both, so put all in http or all in https

**Comment by allancarlosvr** [comment]
Thanks @ddurieux ! i changed my GLPI for 'https' and that's all right! Sucess!

I connected in my GLPI with Grafana

**Comment by ddurieux** [comment]
nice ^^ enjoy now ;)

**Comment by allancarlosvr** [comment]
I included a valid certificate for Https (443) but, the GLPI API dont receive information, with error sync.

Please, look the error in image attached
![errografana](https://user-images.githubusercontent.com/36505009/36810192-c3e739ee-1ca8-11e8-8e39-cab392fb7098.PNG)

**Comment by klmj** [comment]
It seems the certificate does not include the IP address of the system that
host GLPI.
Change your Grafana's configuration to point to FQDN or something else that
is included in certificate's subject or certificate's alternative names.

Or request a new certificate to include IP address 10.99.1.99.

**Comment by ddurieux** [comment]
Any news?

**Comment by ddurieux** [comment]
I close, if required, open a new issue ;)

**Comment by ilsonbaltazar** [comment]
Hi, my integration between grafana and GLPI is working, but when I starts the integration, the glpi user changes his status to: Active = no at GLPI and consequently the conection stops . Have you alredy see this problem? Tks
![sh_55 23-oct 10 31](https://user-images.githubusercontent.com/44403727/47364095-d1f5ca80-d6ae-11e8-8380-708d761dba1d.gif)

**Comment by ddurieux** [comment]
Not unactive it :p 
if put the active to no automatically (so without manual modification), you have a big problem :(

**Comment by ilsonbaltazar** [comment]
Thanks @ddurieux. Could you pass me how I change this configuration to manual?

**Comment by will1402** [comment]
good night
I'm having trouble setting up glpi and grafana
is returning the following error

**Cross-Origin Request Blocked: add right headers in your apache/nginx like 'App-Token' and 'Session-Token'**

I'm using Grafana v5.4.3 (6539180) and GLPI 9.3.3 - on Centos7 server and httpd 

I've already altered httpd.conf as directed, but I still get the message, any tips on what to do?

**Comment by ddurieux** [comment]
See messages of this topic, there is information. If not works, check webserver logs to see if you have errors

**Comment by saragrecia** [comment]
Hey!!!
I have this problem could you help me?
![grafana](https://user-images.githubusercontent.com/51198969/58649553-64f88200-82da-11e9-91eb-2d19343dd3a1.png)

**Comment by ddurieux** [comment]
You have a 401, so check the web server logs / GLPI logs
