### ISSUE TITLE
How to Enable API REST on GLPI to use as DataSource

### ISSUE THREAD

**Issue by arthurvivareal** [ddurieux/glpi_app_grafana#12]
Hi all,
I am newbie with APIs/GLPI, i would like to know how can i enable the Rest API to use on Grafana.

I am facing this error:
![image](https://user-images.githubusercontent.com/23404572/32017843-c316fdde-b9a6-11e7-8901-d617986661f7.png)

**Comment by ddurieux** [comment]
In GLPI, go in menu `Setup > general` and after in tab `api`

**Comment by arthurvivareal** [comment]
Uwo, Thanks a lot, now i need get the App-token and UserToken... Sorry fot that... could you help me?

**Comment by ddurieux** [comment]
the app-token is in this menu, for usertoken, need go in top in your profile/preference and you will be able generate it

**Comment by arthurvivareal** [comment]
Ok, i got it!
Now i have this error
![image](https://user-images.githubusercontent.com/23404572/32019770-02c53936-b9ad-11e7-8c3a-b3103564238e.png)
Thanks for your HELP!

**Comment by ddurieux** [comment]
You have all information in the message :D

**Comment by arthurvivareal** [comment]
Thanks! I will study how add Header set Access-Control-Allow-Origin on my apache!
