### ISSUE TITLE
GLPI Datasource - Internal server error.

### ISSUE THREAD

**Issue by dmalagap** [ddurieux/glpi_app_grafana#13]
Hello Ddurieux,

I haven one problem with the  integration between GLPI and Grafana:

![internal server error](https://user-images.githubusercontent.com/34477412/33883069-9e71484a-df3a-11e7-8ca7-6b8a065f0a94.png)

But I'm getting this error when I want to save the DataSource.

Also I just try with Basic Auth, but the same problem still appear.

Do you know what can be the problem?

Thank you.

Regards.

**Comment by ddurieux** [comment]
Any news? errors in php / glpi logs ?

**Comment by ddurieux** [comment]
No more info, I close

**Comment by raimundo-infraestrutura** [comment]
Olá vc conseguiu conectar glpi com grafana
