### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by mohierf** [ddurieux/glpi_app_grafana#14]
With the most recent Grafana:
![image](https://user-images.githubusercontent.com/2932687/35391084-e6e1b8b0-01dd-11e8-9740-e35bb783fa5f.png)

**Comment by ddurieux** [comment]
Because you need put in _Query_ field the search of ticket like 
```
[...]/front/ticket.php?is_deleted=0&criteria%5B0%5D%5Bfield%5D=all&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=&search=Rechercher&itemtype=Ticket&start=0&_glpi_csrf_token=772b74c784efabd95905935cded0a83b
```

**Comment by mohierf** [comment]
Even if I do not search for a specific field ? Please add this to the doc...

**Comment by mohierf** [comment]
Nope! Same result with:
```
....../front/ticket.php?is_deleted=0&criteria%5B0%5D%5Bfield%5D=all&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=&search=Rechercher&itemtype=Ticket&start=0&_glpi_csrf_token=772b74c784efabd95905935cded0a83b
```

**Comment by ddurieux** [comment]
The search with query _all_ not works, you need specify a field to search, but not _all_
