### ISSUE TITLE
Problem with GLPI 9.2.3

### ISSUE THREAD

**Issue by gerpion** [ddurieux/glpi_app_grafana#19]
Hello there,

I configured the datasource and everything it's saying the datasource is working.

Anyway the dashboard is not working.
I'm using the console view in my browser and i got the following error :

![image](https://user-images.githubusercontent.com/15326288/39422164-7b46dad4-4c6c-11e8-9cd6-8bcce54d31bd.png)

![image](https://user-images.githubusercontent.com/15326288/39422190-98de877c-4c6c-11e8-9a6c-abc20b7c77d2.png)

and i cant find what is the problem.

Thanks for your help

**Comment by gerpion** [comment]
Found this :

"Identifiant de champ incorrect dans le critère de recherche; Afficher la documentation dans votre navigateur à http://srvglpi/glpi/apirest.php/#ERROR"

**Comment by ddurieux** [comment]
Seems you have a configuration problem of the API in your webserver

**Comment by gerpion** [comment]
GLPI side ?

**Comment by ddurieux** [comment]
Yes I think

**Comment by gerpion** [comment]
Can we have 2 GLPI datasources on the same server ?

Trying to make it work with 2 totally differents instances of GLPI on same server.

Test works and Prod doesnt

**Comment by ddurieux** [comment]
You are sure the 2 datasources with different API key not use the same URL?

**Comment by gerpion** [comment]
![image](https://user-images.githubusercontent.com/15326288/39426011-5cb2dae8-4c7e-11e8-87cb-5cd6874bbdec.png)

![image](https://user-images.githubusercontent.com/15326288/39426026-6a2bed54-4c7e-11e8-9719-f7ccd18d3885.png)

**Comment by ddurieux** [comment]
Remove the **/** at the end of the URL

**Comment by gerpion** [comment]
On peut continuer en Français si tu veux, je vois que tu es de France.
Vraiment là je ne comprends pas.

Je n'ai aucune erreur quand je créer mes datasources mais je n'ai rien qui marche pour la base de prod.

La différence :
* Base de test : installée avec les sources GLPI
* Base de prod : installation d'une version précise et export/import d'une BDD glpi qui était sur un autre serveur

Dans mon navigateur en mode developpeur, je ne vois pas d'erreur particulière.

Il y a un autre moyen que je ne connaîtrais pas de voir s'il y a un souci ?

J'ai fais un dashboard d'exemple avec des requêtes que j'ai prise dans GLPI :

![image](https://user-images.githubusercontent.com/15326288/39426284-84ef3e6a-4c7f-11e8-958c-eca77f10440f.png)

Dans la partie QUERY, les urls sont ok pour PROD et TEST et si je copie/colle l'url qui est dans QUERY dans un navigateur, j'ai exactement ce que je veux.

Sauf dans Grafana où j'ai toujours 0 pour la prod

**Comment by gerpion** [comment]
le / supprimé et toujours le même résultat

**Comment by ddurieux** [comment]
OK, si c'est un explort/import, essaye de regénérer les clés API (de glpi et du compte utilisateurs)

**Comment by gerpion** [comment]
Alors ça évolue un peu !
J'avais déjà régénéré les clés mais je l'ai quand même fait, on ne sait jamais.

J'ai fais pleiiiiin de test.

Avec le jeton d'API de mon compte utilisateur, je ne vois que les stats me concernant et non pas le global (je suis super admin en récursif partout)
Avec plein d'autre compte avec qui j'ai essayé et qui ont crée plein de ticket, j'ai toujours zéro partout.

**Comment by ddurieux** [comment]
Pour ton compte, vérifie dans tes préférences que **par défaut** t'as bien le profil super-admin su rl'entité racine (+ récursif)

**Comment by gerpion** [comment]
Bon j'ai encore du nouveau très intéressant.
Voila ce que je constate :

Depuis que j'ai fais l'import, j'a crée ticket que j'ai retrouvé dans Grafana.
J'ai demandé à une collègue de créer un ticket de test et bingo on le voit dans les compteurs.

C'est comme si on ne voyait les stats qu'à partir du moment où j'ai fais l'export et du coup pas toute les stats globales des autres tickets.

J’espère que j'arrive à être assez clair.

**Comment by ddurieux** [comment]
Fais attention, dans grafana il y a l'échelle de temps en haut qui peut jouer si tes tickets sont _trop vieux_

Sinon, si tu as des entités, je te conseille de relancer php-fpm (ou ton serveur web si php est géré par lui).

**Comment by gerpion** [comment]
Ah ça commence à devenir pas mal là, merci de ton aide.

Une autre question, quand tu mets un panel par défaut, j'ai cette adresse : 127.0.0.1/glpi090/front/ticket.php?is_deleted=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=all&criteria[1][link]=AND&criteria[1][field]=14&criteria[1][searchtype]=equals&criteria[1][value]=1&search=Rechercher&itemtype=Ticket&start=0

Tu remplaces 127.0.0.1/glpi090 par le début de l'url du serveur où c'est un truc important ?

**Comment by ddurieux** [comment]
c'est celle que j'utilise :p, t'as juste à copier / coller ton URL de recherche GLPI, le plugin grafana va supprimer le début pour composer la bonne URL ;)

**Comment by gerpion** [comment]
Ecoutes c'est parfait, merci beaucoup pour ton aide.
Du coup je suis en train de préparer un gros dashboard pour avoir des stats.

**Comment by ddurieux** [comment]
parfait ;)

**Comment by gerpion** [comment]
Merci encore pour ton aide et surtout ta réactivité :)
Je clôture

**Comment by rachadmeziane** [comment]
@gerpion  @ddurieux Bonsoir, Ou puis-je trouver les requêtes GLPI (pour grafana) svp ? 
Merci par avance
