### ISSUE TITLE
no import dashboards

### ISSUE THREAD

**Issue by Smiley-k** [ddurieux/glpi_app_grafana#2]
there should be a template glpi_grafana
![2017-06-27 18 49 44](https://user-images.githubusercontent.com/11009787/27596902-90cd3258-5b69-11e7-9f77-fa7106e3161f.png)

![image](https://user-images.githubusercontent.com/11009787/27596923-9c61b512-5b69-11e7-9cb5-44f23e95a325.png)

does not import. **Grafana v4.3.2 (commit: ed4d170)**

**Comment by ddurieux** [comment]
I have seen this this afternoon, it's a bug yes ;)

**Comment by ddurieux** [comment]
It's fixed ;)
