### ISSUE TITLE
Using grafana variables with GLPI plugin

### ISSUE THREAD

**Issue by kedson42** [ddurieux/glpi_app_grafana#20]
Hello, is it possible to use Grafana variables with this plugin?

Variables are a great feature, but I can't figure out how to use it with this plugin:

![image](https://user-images.githubusercontent.com/34751754/39944752-2f9fd2b8-553e-11e8-9596-b39f3540df4b.png)

**Comment by ddurieux** [comment]
I don't know, never use them, so not know how works :p

**Comment by ddurieux** [comment]
currently working on the variables ;)

**Comment by kedson42** [comment]
great!

**Comment by danidosreis** [comment]
Very well!
Thank youuu!!!
\0/
