### ISSUE TITLE
GLPI API Error Response: The parameter user_token seems to be invalid.

### ISSUE THREAD

**Issue by edilsonluizsantos** [ddurieux/glpi_app_grafana#21]
Hi Mr Ddurieux

Can you help me?

I installed GPLi plugin in my Grafana server, but o message error in the Datasource configuration.

I have the same error with User Authentication and without user authentication.

In the console brower, the tokens parameters are corrects.
![grafana_plugin](https://user-images.githubusercontent.com/39218298/39958227-8d532a34-55d6-11e8-8354-81ade823d29b.png)
![image](https://user-images.githubusercontent.com/39218298/39958238-ab3ed390-55d6-11e8-8b79-07ea56ffe939.png)
![image](https://user-images.githubusercontent.com/39218298/39958245-bcc2b0b4-55d6-11e8-8b32-5b718e678e84.png)

tks

**Comment by edilsonluizsantos** [comment]
Sorry, i forget the versions.
Grafana 5.1.2 and GLPi plugin 1.2.

tks

**Comment by ddurieux** [comment]
It says your user_token invalid, check the api key in your preferences in GLPI

**Comment by edilsonluizsantos** [comment]
Thanks for your reply!

I put the same key that are in the api_token and user_token on the GLPi parameters.

I checked this itens and the still issue continue.
![glpi_parameters](https://user-images.githubusercontent.com/39218298/39959694-d1b09026-55eb-11e8-9366-cda00ff3a2b2.png)
![grafana_plugin](https://user-images.githubusercontent.com/39218298/39959709-f9e328a6-55eb-11e8-940c-302911ed91f1.png)

**Comment by ddurieux** [comment]
it's the token, not the api key, you have it bellow in GLPI screen (not visible)

**Comment by edilsonluizsantos** [comment]
Hi, David!

Working!!!  

I don't have words that express my gratitude!

tks

**Comment by ddurieux** [comment]
Nice ;)

**Comment by raimundo-infraestrutura** [comment]
> é o token, não a chave da API, você a tem abaixo na tela do GLPI (não visível)

Olá Aonde eu pego token ,não a chave

**Comment by zincyber** [comment]
[raimundo-infraestrutura](https://github.com/raimundo-infraestrutura) beleza? Tu pega em Aministração > Seleciona o usuário e vai em "todos" lá tu vai encontrar um item chamado API Token, nele que tu tem que RE-gerar e vai dar certo

**Comment by abreuti** [comment]
@raimundo-infraestrutura você conseguiu ? passo pelo mesmo problema aqui ainda não consegui resolver.

**Comment by zincyber** [comment]
![aaaaaaaaa](https://user-images.githubusercontent.com/34379083/166077816-9ee8a1d4-5798-4545-9409-afb25726f9d8.gif)

Eu fiz esse gif de um glpi que uso pra testes, da uma olhada que vai dar certo :)
