### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by edilsonluizsantos** [ddurieux/glpi_app_grafana#22]
Hi David.

I have this message in the Fusioninventory Panel.

Can you help me?

![image](https://user-images.githubusercontent.com/39218298/39999119-905f0b2e-575e-11e8-9d78-c1af18fe2c51.png)

**Comment by ddurieux** [comment]
Yes I have this problem too when no data found. I will see that quickly

**Comment by ddurieux** [comment]
Can you give me the query (glpi URL) of this panel ?

**Comment by edilsonluizsantos** [comment]
http://192.168.90.104/glpi/front/computer.php?is_deleted=0&criteria[0][field]=121&criteria[0][searchtype]=contains&criteria[0][value]=&search=Rechercher&itemtype=Computer&start=0

**Comment by edilsonluizsantos** [comment]
In The browser works, but in the grafana don´t work.

**Comment by ddurieux** [comment]
I fixed the problem with replace.
If you have again a problem, or another, check you have _Timerange based on_ defined in the editor of the graph

**Comment by edilsonluizsantos** [comment]
Tks!

2018-06-05 9:05 GMT-03:00 David Durieux <notifications@github.com>:
