### ISSUE TITLE
Server vs. Browser

### ISSUE THREAD

**Issue by Megachip** [ddurieux/glpi_app_grafana#23]
Feels a bit that Server and Browser are switched:

When selecting a server as access I've got the following error:
`GLPI API Error Response: Es gibt keinen aktiven API-Client, der mit Ihrer IP-Adresse in der Konfiguration übereinstimmt. (Client-IP, Client-IP)`
As I'm understanding, when using server no direct request from client to glpi will be made!?
When using Browser:
`Cross-Origin Request Blocked: add right headers in your apache/nginx like 'App-Token' and 'Session-Token'`

GLPI 9.2.3
Plugin 1.1.0
Grafana 5.1.2

**Comment by ddurieux** [comment]
With browser you need configure your Apache or NGINX webserver to allows the CORS

**Comment by ddurieux** [comment]
See #5

**Comment by Megachip** [comment]
But why it shown the IP of the desktop client which accesses grafana and not the ip of grafana?

**Comment by ddurieux** [comment]
in _server_ mode?
