### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by leandrotenorio** [ddurieux/glpi_app_grafana#25]
Hello

How are you?

Can you help me? 

When I configured the plugin return this error...

![image](https://user-images.githubusercontent.com/8218579/41369766-2d02031c-6f1c-11e8-9989-30ae9c3ce967.png)
![image](https://user-images.githubusercontent.com/8218579/41369775-327edcd4-6f1c-11e8-9a70-b1ac550280b2.png)

**Comment by Nicare** [comment]
Hello,

Same here, I've tried with different GLPi version. Twicking with app token and/or user token : same result.
I've cut and paste the IP address shown in the error message to the API application : same result.

I'm able to manually connect from the Grafana machine (using wget for instance). So I don't thing it could be a IP setup issue.

Any idea ?

Thanks

**Comment by ddurieux** [comment]
Grafana on same server than GLPI ?

**Comment by Nicare** [comment]
No different machines

**Comment by ddurieux** [comment]
In configuration in grafana, you had tried in proxy AND direct or only one of both ?

**Comment by Nicare** [comment]
I’ve tried both (server and proxy)

I guess my setup is incompleted to be able to do proxy (CORS setup is missing)

So I prefered focussing on the server way. (I’ll use the dashboard on autonomous screen, limited browser).

Is there some things to get the correct debug logs ?

**Comment by ddurieux** [comment]
Without CORS configuration, it can't works. So check the CORS config (I added doc for that)

**Comment by Nicare** [comment]
Even in server mode ?

I had found a couple of lines to do the setup but I wasn’t able to identify where to add them.

BTW : which GLPi version minimum (I’ve seen a post where you mentionned a fix)

Thanks

**Comment by ddurieux** [comment]
Yes in all cases you need have CORS configured

**Comment by Nicare** [comment]
Ok,

I’ve added this in my glpi.conf file (EON5.1) :
Alias /glpi "/srv/eyesofnetwork/glpi"

<Directory /srv/eyesofnetwork/glpi>
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE"
        Header set Access-Control-Allow-Credentials true
        Header set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization,               
        Accept, Client-Security-Token, Accept-Encoding, App-Token, Session-Token"
        Options None
        AllowOverride Limit Options FileInfo
        Require all granted
</Directory>


Restart the server, and still the same issue.

From the log file not difference between before and after :
192.168.209.137 - - [19/Jun/2018:00:29:39 +0200] "GET /glpi/apirest.php/initSession HTTP/1.1" 400 140
192.168.209.137 - - [19/Jun/2018:00:29:39 +0200] "GET /glpi/apirest.php/initSession HTTP/1.1" 400 140
192.168.209.137 - - [19/Jun/2018:00:29:39 +0200] "GET /glpi/apirest.php/initSession HTTP/1.1" 400 140
192.168.209.137 - - [19/Jun/2018:16:48:30 +0200] "GET /glpi/apirest.php/initSession HTTP/1.1" 400 140

Any idea ?

**Comment by ddurieux** [comment]
Check in 'network' tab of you browser (developper tools) and you can have more information about the error

**Comment by Nicare** [comment]
This is what I've found : 

﻿
![2018-06-19_1936](https://user-images.githubusercontent.com/40391356/41614313-7e12a21c-73f8-11e8-992b-dea26a7947f0.jpg)
grafana_app.ts:59 warning rootScope onAppEvent called without localscope

:3000/api/datasource…oxy/2/initSession:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
2:1 Failed to load https://192.168.209.139/glpi/apirest.php/initSession: Request header field App-Token is not allowed by Access-Control-Allow-Headers in preflight response.
angular.js:12837 GET http://192.168.209.137:3000/api/datasources/proxy/2/initSession 400 (Bad Request)

Doesn't mean things for me :(

**Comment by ddurieux** [comment]
`App-Token is not allowed by Access-Control-Allow-Headers` so not sure the header you have put in apache configuration is in the right place

**Comment by Nicare** [comment]
Oups, missing a refresh, my mistake, this error was with browser mode (which is not my target).

If I do a connection with server mode I only have this error : 
GET http://192.168.209.137:3000/api/datasources/proxy/2/initSession 400 (Bad Request)

**Comment by ddurieux** [comment]
I think it's the same problem

**Comment by Nicare** [comment]
Grrr , it wasn't the correct file :( 

Modifying the correct one fixed "Request header field App-Token" in browser mode. 
It works in browser mode 👍 

192.168.209.1 - - [19/Jun/2018:21:14:52 +0200] "OPTIONS /glpi/apirest.php/initSession HTTP/1.1" 200 -
192.168.209.1 - - [19/Jun/2018:21:14:52 +0200] "GET /glpi/apirest.php/initSession HTTP/1.1" 200 46

But on server mode is still stuck with error 400 : 
192.168.209.140 - - [19/Jun/2018:21:14:24 +0200] "GET /glpi/apirest.php/initSession HTTP/1.1" 400 140

Do you think it could be worth to stop doing SSL and sniff the packets to see what's going on ?

Many thanks for your help

**Comment by ddurieux** [comment]
In server, there is a problem with code in API, you need modify the code in GLPI like in this comment: https://github.com/ddurieux/glpi_app_grafana/issues/10#issuecomment-336712233

**Comment by Nicare** [comment]
Perfect, it works with server option too 👍 👍 👍 

My version was not the same, but the 3 lines solved the issue : 
// retrieve ip of client
      $this->iptxt = (isset($_SERVER["HTTP_X_FORWARDED_FOR"]) ? $_SERVER["HTTP_X_FORWARDED_FOR"]
                                                              : $_SERVER["REMOTE_ADDR"]);
        $spl = explode(',', $this->iptxt);
        if (count($spl) > 1) {
         $this->iptxt = $spl[0];
        }
      $this->ipnum = (strstr($this->iptxt, ':')===false ? ip2long($this->iptxt) : '');_

Great, Thanks, 
Need to play with the query now :)

**Comment by ddurieux** [comment]
Nice ;)
