### ISSUE TITLE
unable to connect to GLPI

### ISSUE THREAD

**Issue by Smiley-k** [ddurieux/glpi_app_grafana#26]
Hi, I have such problem

GLPI API Error Response: session_token is missing or empty; view documentation in your browser in http://help.hub.mydomain.local/apirest.php/#ERROR_SESSION_TOKEN_MISSING

GLPI ver. 9.2.4

**Comment by ddurieux** [comment]
You have defined the session token in the datasource?

**Comment by Smiley-k** [comment]
Yes,

I take the token from the user profile - right ?

![image](https://user-images.githubusercontent.com/11009787/41901415-870f195e-7939-11e8-930e-1078b9a0e7eb.png)

or is it necessary from the basic ?
Home > Setup > General > API clients
![image](https://user-images.githubusercontent.com/11009787/41901517-c7c47912-7939-11e8-9be8-763d592a6870.png)

actually the error itself.

![2018-06-26 12 21 52](https://user-images.githubusercontent.com/11009787/41902239-9f4cd6a8-793b-11e8-8a79-49f1a9248fc7.png)

**Comment by ddurieux** [comment]
App-token is the key in configuration > general > API 
the user-token is the API-token you have in your screen (in the user preferences)

**Comment by Smiley-k** [comment]
but then I have a message.

GLPI API Error Response: user_token may not be valid

**Comment by Smiley-k** [comment]
Sorry I wasn't paying attention, it works now.

**Comment by ddurieux** [comment]
cool ;)
