### ISSUE TITLE
Getting TotalCount instead of count value as count elements

### ISSUE THREAD

**Issue by Nicare** [ddurieux/glpi_app_grafana#27]
Hello,

is there a way to get TotalCount value instead of count value in a panel ?

For instance, on the default Dashboard, I would like to retrieve the Total number of Computers.
Count elements is limited by the windowing system (400 by default) used to limit the number of answers returned during a equest.

If you read the query Inspector, it's possible to see totalcount, but I'm not able to retrieve the info in my panel.

Thanks

**Comment by christophe2049** [comment]
Hi ! 
Similar issue for me, I want to retrieve number of tickets per month , but the value is limited to 400 .
Is There a way to modify the range ?

My request : 

http://127.0.0.1/glpi/front/ticket.php?is_deleted=0&criteria[0][field]=15&criteria[0][searchtype]=equals&_select_criteria[0][value]=0&criteria[0][value]=2018-10&search=Rechercher&itemtype=Ticket&start=0

Thanx

**Comment by ddurieux** [comment]
But in grafana you don't have the limit

**Comment by christophe2049** [comment]
Sorry , what do you mean ?

**Comment by ddurieux** [comment]
How do you know it's limited in 400? because if you have the limit in GLPI, you will not have it into grafana

**Comment by christophe2049** [comment]
When I use the request in URL in glpi , it returns me 767 items, but in grafana it's stuck to 400 elements:

Heres the query inspector result : 


  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/2/search/ticket?is_deleted=0&criteria[0][field]=15&criteria[0][searchtype]=equals&_select_criteria[0][value]=0&criteria[0][value]=2018-01&search=Rechercher&itemtype=Ticket&start=0&forcedisplay[0]=0&range=400-799"
  },
  "response": {
    "totalcount": 767,
    "count": 367,
    "sort": 1,
    "order": "ASC",
    "data": [
      {
        "1": "Installation Microsoft Office",
        "2": 52046,
        "15": "2018-01-18 18:09:03",
        "80": "Entité racine"
} 

....
{
        "1": "zimbra m'informe que mon compte va etre desactiver",
        "2": 51712,
        "15": "2018-01-09 08:08:48",
        "80": "Entité racine"
      }
    ],
    "content-range": "400-766/767"
  }
}

![image](https://user-images.githubusercontent.com/44196104/47017777-7a59db00-d153-11e8-9c55-9798a382f32c.png)

**Comment by ddurieux** [comment]
Ah, ok so I will check the code

**Comment by christophe2049** [comment]
thank you ;-)

**Comment by ddurieux** [comment]
I have found the problem, see fix here: https://github.com/ddurieux/glpi_app_grafana/commit/21d0b1a81911937ae6f6f6f2790a7c0f0fe4b9ac

**Comment by Nicare** [comment]
Thanks David,
I will update my setup too :)

**Comment by christophe2049** [comment]
Thank you very much !
