### ISSUE TITLE
User_Token incorrect

### ISSUE THREAD

**Issue by UpperM** [ddurieux/glpi_app_grafana#28]
Hi ! 

I try to configure the DataSource but i alway get this error :

I checked the older issue  #26 but it's still not working

My Configuration : 

GLPI (9.3)

![image](https://user-images.githubusercontent.com/13823969/44208361-6d733800-a160-11e8-99f4-d54fe84987d6.png)

![image](https://user-images.githubusercontent.com/13823969/44208379-78c66380-a160-11e8-948e-26b1af0daa1c.png)

API User
![image](https://user-images.githubusercontent.com/13823969/44208420-93004180-a160-11e8-89ff-dc6474bf7c1e.png)

Grafana (5.2.1)

![image](https://user-images.githubusercontent.com/13823969/44208815-d909d500-a161-11e8-9af1-9cdf0ddbddb1.png)

![image](https://user-images.githubusercontent.com/13823969/44208545-ee323400-a160-11e8-9866-736d8c633dd1.png)

My GLPI server is on a VPS (OVH) configured in HTTPS.
I enabled the headers_module in the virtual host and in the apache conf

![image](https://user-images.githubusercontent.com/13823969/44208608-2174c300-a161-11e8-89d4-4daccd3cfca8.png)
My GLPI is not in HTTP

Thank.
Merci

**Comment by ddurieux** [comment]
You need activate the field _Activer la connexion avec un jeton externe_, I think must works better after ;)

**Comment by UpperM** [comment]
Thank you !! 

![image](https://user-images.githubusercontent.com/13823969/44216900-6820e800-a176-11e8-9ee7-21cb25385611.png)

Merci beaucoup ;)

**Comment by UpperM** [comment]
So i try to update your dashboard with my params but i get an error

![image](https://user-images.githubusercontent.com/13823969/44217560-09f50480-a178-11e8-9216-b28f6b2178a4.png)
![image](https://user-images.githubusercontent.com/13823969/44217568-0d888b80-a178-11e8-8abd-36eeebe74849.png)

**Comment by ddurieux** [comment]
Great ;)
