### ISSUE TITLE
Problem Integration GLPI + Grafana

### ISSUE THREAD

**Issue by leandrotenorio** [ddurieux/glpi_app_grafana#3]
Hello Mr Ddurieux 

How are you? Can you help me? 

I Installed the plugin GLPI in Grafana, acoording with instructions in page, but,  a message return with error.

Regards

Leandro Tenorio
![screenshot_3](https://user-images.githubusercontent.com/8218579/29173583-20701dc2-7dba-11e7-895f-3628d59c3ebd.png)

**Comment by ddurieux** [comment]
I think the / at the end of the url can be the problem

**Comment by leandrotenorio** [comment]
I corriged the / in the end, but, the error continue. The configurations are corrects? Or needs some other parameter? 

I tried with and without options http auth, proxy, direct and others, the error continue the same.

![screenshot_4](https://user-images.githubusercontent.com/8218579/29196081-96060698-7e08-11e7-9e20-317ea953ea89.png)

**Comment by leandrotenorio** [comment]
The version Grafana is 4.3.2 and GLPI 9.1.2

**Comment by ddurieux** [comment]
Remove the user and password, un-check basic auth and with credential

**Comment by leandrotenorio** [comment]
Hello Mr Ddurieux

The same error,  don´t connect in glpi. 

![screenshot_7](https://user-images.githubusercontent.com/8218579/29214523-1081e052-7e7e-11e7-9104-184c32b01ff2.png)

![screenshot_8](https://user-images.githubusercontent.com/8218579/29214570-3df14ce4-7e7e-11e7-85cb-4afb6aaa4b44.png)

**Comment by ddurieux** [comment]
can you open your browser console and see the error on the api URL ?

**Comment by ddurieux** [comment]
I will try to enhance the error message

**Comment by leandrotenorio** [comment]
Follow image of browser console. 

![screenshot_9](https://user-images.githubusercontent.com/8218579/29223812-48566f0a-7e9e-11e7-9287-0c119aeee736.png)

**Comment by ddurieux** [comment]
So you have an error 400, try:
* define Access in `proxy` and test same with error
* see in your apache and in glpi log if you have errors
* in debug see the tab `network` instead `console` to have more information

**Comment by leandrotenorio** [comment]
Follow the images. 

Log of the glpi and apache not error about webservice. 

![screenshot_10_console_direct](https://user-images.githubusercontent.com/8218579/29227556-a9587240-7eac-11e7-97f9-9ca19c78b57b.png)
![screenshot_10_network](https://user-images.githubusercontent.com/8218579/29227555-a957822c-7eac-11e7-8f91-1b191e1e453a.png)
![screenshot_10_proxy](https://user-images.githubusercontent.com/8218579/29227557-a95867a0-7eac-11e7-9b2f-6f740773d046.png)

**Comment by ddurieux** [comment]
You need add App-Token in headers in your apache config

**Comment by ddurieux** [comment]
I have enhanced the error message #4 ;)

**Comment by grvy** [comment]
Doesnt work with new version of grafana. Old version works. Please update!

**Comment by fulljackz** [comment]
Is it possible to have a configuration example about your post : 

> You  need add App-Token in headers in your apache config

Thanks !

**Comment by ddurieux** [comment]
;)

**Comment by Douglasalex94** [comment]
Hello,

When trying the configuration in Grafana it shows me the error of the attached image. can you help me?

![image](https://user-images.githubusercontent.com/35815084/35406938-672384e6-01f1-11e8-8a26-c7459503338f.png)

**Comment by ddurieux** [comment]
You use apache or nginx ?

**Comment by Douglasalex94** [comment]
Apache

**Comment by ddurieux** [comment]
If I remember, you need add in configuration `Header set...` but not sure about the syntax, I not touch a Apache since 4 years

**Comment by ddurieux** [comment]
Any news?

**Comment by ddurieux** [comment]
See #5
