### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by dani** [ddurieux/glpi_app_grafana#32]
Since version 1.2.0 of the plugin, all my GLPI panels returns the same error:

```
Cannot read property 'number' of undefined
```

With the full stack trace

```
TypeError: Cannot read property 'number' of undefined
    at Array.eval (https://graphes.domain.net/public/plugins/ddurieux-glpi-app/datasource/datasource.js:121:60)
    at eval (https://graphes.domain.net/public/plugins/ddurieux-glpi-app/datasource/datasource.js:60:62)
    at u (https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:68722)
    at https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:69127
    at h.$digest (https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:74824)
    at h.$apply (https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:76638)
    at https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:72697
    at i (https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:21870)
    at https://graphes.domain.net/public/build/vendor.337c125610d33424db4a.js:87:23332
```

Example of query triggering it:
https://tkt.domain.net/front/ticket.php?itemtype=Ticket&sort=2&order=DESC&start=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=notold&criteria[1][link]=AND&criteria[1][field]=15&criteria[1][searchtype]=lessthan&criteria[1][value]=NOW&criteria[2][link]=AND&criteria[2][field]=7&criteria[2][searchtype]=notequals&criteria[2][value]=23

Everything was fine with 1.1.0 (and everything is working again as soon as I downgrade back to 1.1.0)

One thing interesting is that, if I edit the applet, and wait a few seconds without changing anything, then the applet starts working. Even if I go back to the dashboard. It works until à reload the page

Running on CentOS 7, Grafana 5.2.0

**Comment by ddurieux** [comment]
Can you send me your dashboard in json format?

**Comment by dani** [comment]
Mmmhhh, rather strange. My dashboard uses different datasources, so to send it to you with only the relevent info, I copied the dashboard, and removed all panel which don't use the GLPI datasource. And here it's working (after an initial edit -> don't change anything -> return). I'll need to investigate a bit more to have a easy reproducer

**Comment by dani** [comment]
Well, we can close the issue. I have no explanation, but if I just edit all the panels, wait a few seconds without changing anything, got back to the dashboard, and then save the dashboard, everything is working again
