### ISSUE TITLE
Error with zero values

### ISSUE THREAD

**Issue by danidosreis** [ddurieux/glpi_app_grafana#33]
Good Morning,
I am having problems in queries where the value returned is 0 (No items found).
When I add a query where the result is zero, the chart starts to fail.

Ex.:

![image](https://user-images.githubusercontent.com/39527066/47503515-b5899780-d840-11e8-9370-548859d02f2e.png)

![image](https://user-images.githubusercontent.com/39527066/47503529-bae6e200-d840-11e8-808d-f9ea7793f274.png)

![image](https://user-images.githubusercontent.com/39527066/47503659-07322200-d841-11e8-9570-b69f61d3de27.png)

**Comment by ddurieux** [comment]
Hello, can you send me:
* the type of panel
* the 2 queries

Thanks

**Comment by leandroferreirait** [comment]
Type: Graph
queries: 
http://192.168.0.10/glpi/front/ticket.php?is_deleted=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=all&criteria[1][link]=AND&criteria[1][field]=14&criteria[1][searchtype]=equals&criteria[1][value]=2&criteria[2][link]=AND&criteria[2][field]=15&criteria[2][searchtype]=morethan&_select_criteria[2][value]=BEGINMONTH&criteria[2][value]=BEGINMONTH&search=Pesquisar&itemtype=Ticket&start=0&_glpi_csrf_token=151fc167e141023618dc5dd90b3


![image](https://user-images.githubusercontent.com/37178674/48004072-f742f980-e0ee-11e8-9c8f-e49fdf8f3632.png)

**Comment by danidosreis** [comment]
Hello ddurieux,

Panel: Anyone, for exemple "Pie Chart"

Queries:

https://10.0.0.20/front/ticket.php?is_deleted=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=notold&criteria[1][link]=AND&criteria[1][field]=14&criteria[1][searchtype]=equals&criteria[1][value]=1&criteria[2][link]=AND&criteria[2][field]=18&criteria[2][searchtype]=lessthan&_select_criteria[2][value]=2DAY&criteria[2][value]=2DAY&criteria[3][link]=AND&criteria[3][field]=80&criteria[3][searchtype]=notunder&criteria[3][value]=5&criteria[4][link]=AND&criteria[4][field]=8&criteria[4][searchtype]=contains&criteria[4][value]=ms&search=Pesquisar&itemtype=Ticket&start=0&_glpi_csrf_token=e52dbcc436d70f2198f72bb50de98212

![image](https://user-images.githubusercontent.com/39527066/48012802-fd929f00-e109-11e8-9468-4ca67c3ee1df.png)

**Comment by ilsonbaltazar** [comment]
Good question. I have the same problem. I am not able to use the pie chart precisely because we have returns equal to NULL and these returns "break" the graphs.

**Comment by ddurieux** [comment]
I will check it in couple of days

**Comment by danidosreis** [comment]
Fixed with c450fcf fix and update to 1.3

![image](https://user-images.githubusercontent.com/39527066/48155668-ad0a7580-e2b2-11e8-9bf2-1bb92ab393f2.png)

**Comment by ddurieux** [comment]
Nice, is other users have this problem solved with the version 1.3 released couple hours ago ?

**Comment by ilsonbaltazar** [comment]
Solved with the version 1.3 too.

**Comment by ddurieux** [comment]
Very nice, I close this issue ;)
