### ISSUE TITLE
user not properly displayed in table

### ISSUE THREAD

**Issue by romulf** [ddurieux/glpi_app_grafana#43]
Hello,
I'm using a dashboard based on your exemple but some user information are not properly displayed in the table " Last Ticket".
for exemple "Tehnicien" column display:
LE TIEC ERWAN <a id='tooltiplink492698493' href='/front/user.form.php?id=9140'><span id='tooltip492698493' class='fa fa-info pointer'></span></a>

I don't have issue with the column "demandeur"

I'm using  grafana 5.3.2 with glpi plugin 1.3.0
glpi server version is 9.3.2 

![grafana_glpi](https://user-images.githubusercontent.com/12697224/54353454-665bcc00-4654-11e9-9c85-c469633790cf.png)

**Comment by romulf** [comment]
find the solution...
i need to modify column Styles....

**Comment by ddurieux** [comment]
nice :)
