### ISSUE TITLE
incorrect values when using url 

### ISSUE THREAD

**Issue by phamorais** [ddurieux/glpi_app_grafana#68]
Hey guys!
My scenario is:
- GLPI 9.5.5
- Graphane 7.4.3
- Graphana GLPI 1.3.1 Plugin

When making a filter in GLPI (tickets assigned to Group > XPTO), Im get 63

![image](https://user-images.githubusercontent.com/35368369/135092082-f27b8157-3f73-43ee-ba8c-4e781649c9e7.png)

But then put the URL in grafana, I get incorrect values

![image](https://user-images.githubusercontent.com/35368369/135092285-b8b64ea5-abfa-417c-a026-85479c6bfcb5.png)

What can it be?

**Comment by ddurieux** [comment]
Do you have entities in GLPI?

**Comment by phamorais** [comment]
@ddurieux 

No.
There is only one Entity (root).

And the service teams are separated by Groups.

**Comment by phamorais** [comment]
@ddurieux 

When trying to inspect the Query, I get this

![image](https://user-images.githubusercontent.com/35368369/135113395-9bb8a547-194e-407b-b2ac-4c6ac9e56e11.png)

However all tokens are configured.

**Comment by ddurieux** [comment]
Ah found, set the "timerange based on" behind because it filter by default on creation date

**Comment by phamorais** [comment]
@ddurieux 

the field "timerange based on" have values "undefined". Should there be any other option?

![image](https://user-images.githubusercontent.com/35368369/135114403-7bc14607-8886-4d1b-b5cc-f497129c3ee2.png)

**Comment by ddurieux** [comment]
Ah, so I must publish the version compatible , sorry for the problem, forgotten publish it ;(

**Comment by phamorais** [comment]
@ddurieux 

No problem. I'll be waiting for the new version :)

I realized that to work around my problem with the current version, grafana was using "relative time" the information below can default

![image](https://user-images.githubusercontent.com/35368369/135116059-dc41f3b0-cdc4-4d8d-938f-24057084bea9.png)

However, changing to "10y" brought the amount of data I needed

![image](https://user-images.githubusercontent.com/35368369/135116253-98442dc0-a5fb-4674-9410-ccfe9af79c59.png)

**Comment by phamorais** [comment]
> Ah, so I must publish the version compatible , sorry for the problem, forgotten publish it ;(

@ddurieux Hi!

will you publish a new version of the plugin?

**Comment by ddurieux** [comment]
The plugin don't work on Grafana8, I'm working on code to be compatible. Need few days more

**Comment by LordFPL** [comment]
Hello @ddurieux  :) Any news for new version ?

**Comment by phamorais** [comment]
Not more interessed.
